log4r_config:
  # define all loggers ...
  loggers:
    - name      : production
      level     : DEBUG
      trace     : 'false'
      outputters :
      - datefile
    - name      : development
      level     : DEBUG
      trace     : 'true'
      outputters :
      - datefile
    - name      : test
      level     : DEBUG
      trace     : 'true'
      outputters :
      - datefile
    - name      : mongoid
      level     : DEBUG
      trace     : 'true'
      outputters :
      - datefile

  # define all outputters (incl. formatters)
  outputters:
  - type: DateFileOutputter
    name: datefile
    dirname: "log"
    file: "my_log" # this will be overrided by rails' config.
    formatter:
      date_pattern: '%H:%M:%S'
      pattern     : '%d %l: %m '
      type        : PatternFormatter

#  - type: FileOutputter
#    name: file_out
#    filename: "log4r.log"
#    formatter:
#      date_pattern: '%Y-%m-%d %H:%M:%S'
#      pattern     : '%d %l: %m '
#      type        : PatternFormatter

